apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: teamjaf/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/auth-depl.yaml
